server:
  port: 9000
  context-path: /beerhouse
  
spring:
  h2:
    console:
      enable: true
      path: /h2-console      

  
  datasource: 
    url: jdbc:h2:file:./data/app_db;
    username: sa
    password:
    
  jpa: 
    hibernate:
      ddl-auto: update
    show-sql: true
      
  properties:
    hibernate:
      format_sql=\:true
      
    